routes/admin.php
<?php

use App\Http\Controllers\admin\WinController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest', 'namespace' => 'admin'], function () {
    Route::get('', 'LoginController@index');
    Route::any('', 'LoginController@index')->name('admin_login');
    Route::post('main/checklogin', 'LoginController@checklogin');
    Route::get('register', 'LoginController@register')->name('register');
    Route::post('register', 'LoginController@store');
    Route::get('verify/{user:id}', 'LoginController@verify')->name('verify');
    Route::post('verify/{user:id}', 'LoginController@verifyed');
    Route::get('resend/{user:id}', 'LoginController@resend')->name('resend');
});
Route::group(['middleware' => 'auth', 'namespace' => 'admin'], function () {

    // Dashboard
    Route::get('', 'DashboardController@index');
    Route::get('/home', 'DashboardController@index')->name('admin_home');

    // User 
    Route::post('user/delete', 'UsersController@destroyAll');
    Route::get('user/status/{user:id}', 'UsersController@status')->name('user.status');
    Route::post('state/delete', 'StateController@destroyAll');
    Route::post('city/delete', 'CityController@destroyAll');
    Route::post('role/delete', 'RoleController@destroyAll');

    Route::get('search/order', 'OrderController@search')->name('order.search');
    Route::get('export/order', 'OrderController@export')->name('order.export');

    Route::post('order/delete', 'OrderController@destroyAll');
    Route::get('order/status/{order}', 'OrderController@change_status')->name('order_status');

    Route::get('order/status/{id}', 'OrderController@changestatus');
    Route::get('order/pdf/{id}', 'OrderController@invoicepdf');

    // Master 
    Route::resources([
        'state'        => 'StateController',
        'city'         => 'CityController',
        'role'         => 'RoleController',
        'order'      => 'OrderController',
        'user'         => 'UsersController',
    ]);

    // setting 
    Route::resource('setting', 'SettingController');
    Route::get('logout', 'LoginController@logout')->name('admin_logout');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/migrate', function () {
    \Artisan::call('migrate');
    return 'migrate';
});
Route::any('admin', function () {
    return false;
});
// Route::get('/passport', function () {
//     $exitCode = Artisan::call('passport:install');
//     return 'clearede';
// });


Route::get('', 'HomeController@index')->name('home');

resources/views/admin/common/TopHeader.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form> -->

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <!-- <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      Dropdown - Messages
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li> -->

    <!-- Nav Item - Alerts -->
    <!-- <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>

                <span class="badge badge-danger badge-counter">3+</span>
              </a>

              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">Alerts Center</h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li> -->

    <!-- Nav Item - Messages -->
    <!-- <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li> -->

    <!-- <div class="topbar-divider d-none d-sm-block"></div> -->

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"></span>

        <img class="img-profile rounded-circle" src="{{ url('imgs/admin.png') }}">
         <!-- {{ auth()->user()->name }} -->
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <!-- <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a> -->
        @if(auth()->user()->role_id == 1)
        <a class="dropdown-item" href="{{ url('admin/setting/1/edit') }}">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <!-- <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a> -->
        <div class="dropdown-divider"></div>
        @endif
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

resources/views/admin/common/footer.blade.php
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{{ route('admin_logout') }}">Logout</a>
      </div>
    </div>
  </div>
</div>


{{ HTML::script('assets/vendor/jquery/jquery.min.js') }}
{{ Html::script('https://checkout.razorpay.com/v1/checkout.js')}}
{{ HTML::script('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}
{{ HTML::script('assets/vendor/jquery-easing/jquery.easing.min.js') }}
{{ HTML::script('assets/js/sb-admin-2.min.js') }}
{{ HTML::script('datatables/jquery.dataTables.min.js') }}
{{ HTML::script('datatables/dataTables.bootstrap4.min.js') }}
{{ HTML::script('assets/js/validation.js') }}
{{ HTML::script('assets/js/tinymce.min.js') }}
{{ HTML::script('assets/js/select-script.js') }}
{{ HTML::script('assets/js/angular-search.js') }}
{{ HTML::script('datatables/datatables-demo.js') }}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

{{ HTML::script('assets/js/custom-script.js') }}
{{ HTML::script('js/custom-script.js') }}
<script type="text/javascript">
  $(document).ready(function() {
    var token = '{{ csrf_token() }}';
    $('#delete_all').on('click', function(e) {
      e.preventDefault();

      var allVals = [];
      $(".sub_chk:checked").each(function(e) {
        allVals.push($(this).attr('data-id'));
      });
      if (allVals.length <= 0) {
        alert("Please select row?");
      } else {
        let check = confirm("Are you sure you want to delete this row?");
        let form = $(this).closest('form');

        if (check) {
          var join_selected_value = allVals.join(",");

          $.ajax({
            url: $(this).data('url'),
            headers: {
              'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            type: 'POST',
            data: form.serialize(),
            success: function(data) {
              location.reload();
            }
          });
        }
      }
    });
  });


  function statuschange(self) {
    let status = self.value,
      url = $(self).data('url');

    window.location = url + "/?field=status&status=" + status;
  }
</script>
<script>
  $(function() {
    $("#datepicker").datepicker({
      minDate: 0
    });
  });
</script>
<script>
  $(function() {
    $(document).on('change', 'select.weight-select', function() {
      var pid = $(this).val();
      // var selectedCountry = s.val();
      var value = $(this).find('option:selected').attr('data-pc');
      $("#city_pc").val(value);
    });
    // $("#order_search").on('keyup', function() {
    //   $('#orderForm').submit();
    // });

  });
</script>

<script type="text/javascript">
  $(document).ready(function() {
    $(".input-add").click(function() {
      var html = $(".clone").html();
      $(".increment").after(html);
    });
    $("body").on("click", ".input-remove", function() {
      $(this).parents(".control-group").remove();
    });
  });
</script>


<script>
  $('#rzp-footer-form').submit(function(e) {
    var button = $(this).find('button');
    var parent = $(this);
    button.attr('disabled', 'true').html('Please Wait...');
    $.ajax({
      method: 'get',
      url: this.action,
      data: $(this).serialize(),
      complete: function(r) {
        console.log('complete');
        //console.log(r);
      }
    })
    return false;
  })
</script>

<script>
  // let baseUrl = $('#base_url').data('url');

  function demoSuccessHandler(transaction) {
    let form = $('#checkoutForm')[0];

    // You can write success code here. If you want to store some data in database.
    $("#paymentDetail").removeAttr('style');
    if (transaction) {
      $('#paymentID').val(transaction.razorpay_payment_id);
    }

    let formData = new FormData(form);
    let file = $('input[type=file]')[0].files[0];
    formData.append('file', file);

    $.ajax({
      method: 'post',
      url: "{!! route('order.store') !!}",
      processData: false,
      contentType: false,
      data: formData,
      success: function(r) {
        if (r.status) {
          var base_url = window.location.origin + '/' + window.location.pathname.split('/')[1] + '/';
          window.location = base_url + "admin/home";
          console.log('complete');
        }
      }
    })
  }

  function razor_py(price) {
    var options = {
      key: "{{ env('RAZORPAY_KEY') }}",
      amount: price * 100,
      name: 'Printing Services',
      description: 'Printing Services',
      image: '',
      prefill: {
        "email": "{{ @Auth::user()->email }}",
        "contact": "{{ @Auth::user()->mobile }}"
      },
      handler: demoSuccessHandler
    }

    window.r = new Razorpay(options);
    r.open();
  }

  $(document).on('submit', '#checkoutForm', function(e) {
    e.preventDefault();
    is_valid = $(this).is_valid();
    if (is_valid) {
      let order_price = $('#inquery_price').data('price');
      $('#order_price').val(order_price);
      let order_gst_price = $('#inquery_gst').data('price');
      $('#order_gst_price').val(order_gst_price);
      let order_total_price = $('#inquery_total_price').data('price');
      $('#order_total_price').val(order_total_price);
      razor_py(order_total_price);
    }
  });
</script>

</body>

</html>

resources/views/admin/common/header.blade.php
@php
$setting = App\Model\Setting::find(1);
@endphp
<!DOCTYPE html>
<html>

<head>
    <base href="{{ url('/') }}">
    <title>Admin | {{ $title }}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Pankaj Choudhary">
    <link rel="icon" href="{{ url('imgs/favicon/'.$setting->favicon) }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="baseurl" content="{{ url('/') }}">
    <!--- add style sheet ----->

    {{ HTML::style('assets/vendor/fontawesome-free/css/all.min.css') }}
    {{ HTML::style('assets/css/bootstrap-select.min.css') }}
    {{ HTML::style('datatables/dataTables.bootstrap4.min.css') }}
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    {{ HTML::style('assets/css/sb-admin-2.min.css') }}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>




</head>

<body class="">
<!-- <body class="sidebar-toggled"> -->

resources/views/admin/common/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
<!-- <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar"> -->
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('admin/home') }}">
    <!-- <img src="{{ url('imgs/logo/logo.png') }}" alt="" style="max-height: 50px;"> -->
    {{ auth()->user()->role_id == 1 ? 'Admin Panel' : auth()->user()->name }}
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{{  url('admin/home') }}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <hr class="sidebar-divider">
  @if(auth()->user()->role_id == 1)
  <div class="sidebar-heading">
    Master
  </div>

  <!-- <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#master" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-folder"></i>
      <span>Master</span>
    </a>
    <div id="master" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item" href="{{ route('state.index') }}">State</a>
        <a class="collapse-item" href="{{ route('city.index') }}">City</a>
        <a class="collapse-item" href="{{ route('role.index') }}">Role</a>
      </div>
    </div>
  </li> -->

  <li class="nav-item">
    <a class="nav-link" href="{{ route('order.index') }}">
      <i class="fas fa-fw fa-luggage-cart"></i>
      <span>Order</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('user.index') }}">
      <i class="fas fa-fw fa-users"></i>
      <span>User</span></a>
  </li>
  @endif
  @if(auth()->user()->role_id != 1)

  <li class="nav-item">
    <a class="nav-link" href="{{ route('order.create') }}">
      <i class="fas fa-fw fa-luggage-cart"></i>
      <span>Add Order</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('order.index') }}">
      <i class="fas fa-fw fa-luggage-cart"></i>
      <span>Orders</span></a>
  </li>
  @endif

  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    User
  </div>
  <!-- Nav Item - Utilities Collapse Menu -->

  @if(auth()->user()->role_id == 1)
  <li class="nav-item">
    <a class="nav-link" href="{{ url('admin/setting/1/edit') }}">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Setting</span></a>
  </li>

  @endif


  <li class="nav-item">
    <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt fa-chart-area"></i>
      <span>Logout</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->